# Generated by Django 5.1.4 on 2024-12-06 14:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название фильма', max_length=150, verbose_name='Название фильма')),
                ('description', models.TextField(help_text='Напишите описание фильма', verbose_name='О фильме')),
                ('producer', models.CharField(blank=True, help_text='Укажите режиссера', max_length=150, verbose_name='Режиссер')),
                ('years_movi', models.IntegerField(help_text='укажите год выпуска фильма', validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2024)], verbose_name='Год выпука')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['years_movi'],
            },
        ),
    ]
