# Generated by Django 5.1.4 on 2024-12-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(help_text='Укажите название фильма', max_length=150, unique=True, verbose_name='Название фильма'),
        ),
    ]
